# Generated by Django 2.1.1 on 2018-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180909_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=1028)),
                ('response', models.CharField(max_length=1018)),
            ],
        ),
    ]
