# Generated by Django 2.1.1 on 2018-09-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180909_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='person',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
