# Generated by Django 2.1.1 on 2018-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='post',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
