# Generated by Django 2.1.1 on 2018-09-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0004_auto_20180905_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsideBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(through='yerba_mat.InsideBasket', to='yerba_mat.Product'),
        ),
        migrations.AddField(
            model_name='insidebasket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yerba_mat.Basket'),
        ),
        migrations.AddField(
            model_name='insidebasket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yerba_mat.Product'),
        ),
    ]
