# Generated by Django 2.1.1 on 2018-10-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0003_auto_20180915_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidebasket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yerba_mat.Basket'),
        ),
        migrations.AlterField(
            model_name='insidebasket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yerba_mat.Product'),
        ),
    ]
