# Generated by Django 2.1.1 on 2018-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0006_auto_20180902_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='pictures/None/no-img.jpg', null=True, upload_to='pictures/', verbose_name='pictures'),
        ),
    ]
