# Generated by Django 2.1.1 on 2018-09-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0008_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/', verbose_name='pictures'),
        ),
    ]
