# Generated by Django 2.1.1 on 2018-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0012_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
