# Generated by Django 2.1.1 on 2018-09-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yerba_mat', '0013_auto_20180904_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street',
        ),
    ]
